### ISSUE TITLE
Glyph tab NAMES tweak

### ISSUE THREAD

**Issue by wojas007** [bkader/Talented_WoTLK#1]
Hey!
I really like how glyph tabs are behaving in your version : )

However names of glyph tabs work a bit weird and they also could be changed so they are less confusing:

![image](https://user-images.githubusercontent.com/55255393/110238381-a30be680-7f41-11eb-8fd9-17a0927d5a57.png)

In my opinion it would be better if:
1. When primary spec is active -> Glyph tab 1 name: Active spec glyphs
Glyph tab 2 name: Alternate spec glyphs (or Secondary spec glyphs)

2. When secondary spec is active-> Glyph tab 2 name: Active spec glyphs
Glyph tab 1 name: Alternate spec glyphs (or Primary spec glyphs)

Either way - names should follow active spec somehow.

Regards,
Wojas

**Comment by bkader** [comment]
Hi @wojas007! Have you checked this setting?

![Talented_GlyphPolicy](https://user-images.githubusercontent.com/4732702/110241023-f3d60c00-7f4e-11eb-9306-4d34525b965b.png)
