### ISSUE TITLE
Small overlap in the new (better) smaller UI

### ISSUE THREAD

**Issue by wojas007** [bkader/Talented_WoTLK#2]
It's me - annoying Wojas again...

There is very small overlap in the new - very cool looking - small UI.
![image](https://user-images.githubusercontent.com/55255393/110238539-72787c80-7f42-11eb-8ca3-7e7337767939.png)

Only shown when you choose previously saved talents.

Regards,
Wojas

**Comment by bkader** [comment]
Hello @wojas007 !
This was already fixed in [this commit](https://github.com/bkader/Talented_WoTLK/commit/75e03a6f428542a7bb2caa488bd2c80504ac4846)!
