### ISSUE TITLE
Glyphs are not exported in final url

### ISSUE THREAD

**Issue by CraftedRO** [bkader/Talented_WoTLK#5]
Glyphs are still not exported in final generated url.
https://wotlk.evowow.com/?talent#IZZVbhqr0d
https://www.wotlkdb.com/?talent#IZZVbhqr0d
https://truewow.org/talent-calculator#IZZVbhqr0d

![WoWScrnShot_100121_232908](https://user-images.githubusercontent.com/24683355/135682605-8bac181a-4606-44ca-9f4d-4ee059376d62.jpg)

**Comment by bkader** [comment]
@CraftedRO glyphs were never exported in any version I checked. Closing the issue.
